bf16: true
cutoff_len: 4096
dataset: schwan_icep_sft_train
dataset_dir: /home/hcai-admin/DaksithaWasHere/schwan-finetune/data/llamafactory
do_train: true
eval_dataset: schwan_icep_sft_val
eval_steps: 500
eval_strategy: steps
finetuning_type: lora
flash_attn: fa2
gradient_accumulation_steps: 8
learning_rate: 2.0e-05
logging_steps: 10
lora_alpha: 32
lora_dropout: 0.05
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
model_name_or_path: Qwen/Qwen2.5-Omni-7B
num_train_epochs: 3
output_dir: /home/hcai-admin/DaksithaWasHere/schwan-finetune/models/qwen2_omni/icep_sft_full
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
preprocessing_num_workers: 8
report_to: wandb
save_steps: 500
stage: sft
template: qwen2_omni
trust_remote_code: true
val_size: 0
video_maxlen: 64
warmup_steps: 250
